web:
  restart: "no"
  build: .
  dockerfile: Dockerfile.web
  ports:
    - "8000:8000"
  volumes:
    - ./:/usr/src/app
    - ${HOME}/.ssh:/root/.ssh
  env_file:
    - .env
    - .env.secret
  environment:
    - PYTHONPATH=/usr/src/app
    - FLASK_APP=/usr/src/app/deployer/__init__.py
  command: ./bin/start_web

celery:
  build: .
  dockerfile: Dockerfile.web
  volumes:
    - ./:/usr/src/app
    - ${HOME}/.ssh:/root/.ssh
  env_file:
    - .env
    - .env.secret
  environment:
    - PYTHONPATH=/usr/src/app
    - FLASK_APP=/usr/src/app/deployer/__init__.py
  command: celery -A deployer.tasks.celery worker --loglevel=debug

nginx:
  restart: always
  build: .
  dockerfile: Dockerfile.nginx
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web
